export const Base = "https://dev.dsa-cloud.net/dsa/api/";
// export const Base = "/dsa/api/";
export const COUNTRY_BASE_URL = "https://dev.dsa-cloud.net/web/";
// export const COUNTRY_BASE_URL = "/web/";
export const DomainURL = "https://dev.dsa-cloud.net/";
// export const DomainURL = "https://dsa-cloud.net/";
const API = {
  Auth: {
    Login: `${Base}account/login`,
    Signup: `${Base}account/signup`,
    ResetPass: `${Base}account/passreset`,
    LOGOUTURI: `${Base}account/logout`,
    CountriesList: `${COUNTRY_BASE_URL}resources/countrylist.json`,
    ProfileLogo: `${Base}account/logo`,
  },
  Dashboard: {
    graphData: `${Base}players/status`,
    StorageStatus: `${Base}account/storage/status`,
  },
  Monitor: {
    Players: `${Base}players`,
  },
  LocationAndPlayer: {
    Screenshot: `${Base}players/gcm/screen_shot`,
    RequestLogs: `${Base}players/gcm/request_report`,
    SendTrigger: `${Base}players/tp/trigger`,
    TriggerHistory: `${Base}players/pushytriggers`,
    SendConfiguration: `${Base}players/gcm/send_configurations`,
    PurgeUnused: `${Base}players/gcm/recycle`,
    DeleteResync: `${Base}players/gcm/reset`,
    StartPlayer: `${Base}players/gcm/launch_player`,
    StopPlayer: `${Base}players/gcm/quit_sbp`,
    ProofOfPlayRequest: `${Base}players/gcm/request_proof_of_play`,
    Sync: `${Base}players/gcm/new_playlist`,
    WithAll: `${Base}location/withall`,
    PlayersLog: `${Base}log/players`,
    TemplateData: `${Base}template`,
    SendContent: `${Base}players/gcm/new_template`,
    Players: `${Base}players/`,
    CurrentUser: `${Base}account/getcurrentuser`,
    InstallUpdate: `${Base}players/gcm/install_update`,
    RebootPlayer: `${Base}players/gcm/reboot`,
  },
  Gallery: {
    Tags: `${Base}tags`,
    Tag: `${Base}gallery/tag`,
    Url: `${Base}gallery/url`,
    DetailTags: `${Base}gallery/tags`,
    DeleteTags: `${Base}gallery/remove`,
    Gallerydata: `${Base}media/gallery`,
    TagUntag: `${Base}tags/gallery`,
    DeleteUserTags: `${Base}tags/`,
    UploadMedia: `${Base}gallery/uploadfile`,
    UploadAUXFile: `${Base}gallery/uploadauxfile`,
    ReplaceMedia: `${Base}gallery/replacefile`,
    ReplaceAuxFile: `${Base}gallery/replaceauxfile`,
    CheckPDFReady: `${Base}gallery/checkPDFReady/`,
  },
  Newsboard: {
    News: `${Base}newsboard/getall`,
  },

  Playlist: {
    PlaylistSide: `${Base}playlist`,
    NewPlaylist: `${Base}playlist`,
    DuplicatePlaylist: `${Base}playlist/duplicate`,
    Subplaylist: `${Base}media/playlist/subplaylist/`,
    PlaylistById: `${Base}media/playlist/`,
    PlayListData: `${Base}playlist/`,
    DeletePlaylist: `${Base}playlist/`,
    DeletePlaylistContent: `${Base}media/ids`,
    EditPlaylist: `${Base}playlist/`,
    ReplaceSubplaylist: `${Base}media/replace/subplaylist/`,
    ReplaceWithMedia: `${Base}media/replace/media/`,
    SyncPlaylist: `${Base}players/gcm/new_playlist`,
    PurgePlaylist: `${Base}playlist/subplaylistcount/`,
    GetPlayers: `${Base}players`,
    SendToPlayer: `${Base}players/gcm/new_playlist`,
    PlayerLocation: `${Base}players/filters/location`,
    PlayerLocationList: `${Base}location`,
    PlayerContent: `${Base}players/filters/content_type`,
    PlayerStatus: `${Base}players/filters/deviceStatus`,
    TagById: `${Base}gallery/tag`,
    PlaylistLocation: `${Base}location`,
    AddMedia: `${Base}media/playlist/`,
    TriggerTypes: `${Base}media/triggertypes`,
    GetTemplate: `${Base}template`,
    DeleteTags: `${Base}tags/untag/`,
    ChangeOrder: `${Base}media/change`,
    weatherConditions: `${Base}media/weather/conditions`,
    playlistDuration: `${Base}playlist/duration/`,
  },
  Geolocation: {
    location: `${Base}location`,
  },
  AdminSetting: {
    licence: `${Base}license`,
    logoPreview: `${Base}theme/logo/preview`,
    changePassword: `${Base}account/passchange`,
    addLisence: `${Base}license/activate`,
    localUser: `${Base}account/localusers`,
    addLocalUser: `${Base}account/localuser/signup`,
    deletUser: `${Base}users/`,
    editUser: `${Base}account/localuser/edit/`,
    players: `${Base}players`,
    PlaylistLocation: `${Base}location/`,
    NewLocation: `${Base}location`,
    EditLocation: `${Base}location/default`,
    SusspendUser: `${Base}account/localuser/suspend/`,
    ActivateUser: `${Base}account/localuser/activate/`,
    PasswordRest: `${Base}account/localuser/passreset/`,
    ResendEmail: `${Base}location/resendemail/`,
    Theme: `${Base}theme`,
    NewTheme: `${Base}theme/localuser/current/`,
    EditAccount: `${Base}account/edit`,
    EditAccount: `${Base}account/edit`,
    PlayListAllowed: `${Base}playlist/localuser/allowed/`,
    AllowNewPlaylist: `${Base}playlist/localuser/allow/`,
    DissAllowNewPlaylist: `${Base}playlist/localuser/disallow/`,
    PlayListPermissons: `${Base}permissions/playlist`,
    PlayListDisAllowed: `${Base}playlist/localuser/disallowed/`,
    TemplateAllowed: `${Base}template/localuser/allowed/`,
    TemplateDissAllowed: `${Base}template/localuser/disallowed/`,
    AllowNewTemplate: `${Base}template/localuser/allow/`,
    DissAllowNewTemplate: `${Base}template/localuser/disallow/`,
    LocationAllowed: `${Base}location/localuser/allowed/`,
    LocationDissAllowed: `${Base}location/localuser/disallowed/`,
    AllowNewLocation: `${Base}location/localuser/allow/`,
    DissAllowNewLocation: `${Base}location/localuser/disallow/`,
    LocationPermissons: `${Base}permissions/location`,
    LocalUserPermissons: `${Base}permissions/user`,
    GalleryTags: `${Base}tags/permission/user/`,
    AddUserTags: `${Base}tags/user/add/`,
    UnregisterPlayer: `${Base}players/unregister`,
    ChangeTheme: `${Base}theme/user/current/`,
    PlayerInLocation: `${Base}players/location/`,
    GenerateApiToken: `${Base}users/generateapitoken`,
  },
  Logs: {
    logsSide: `${Base}log/logidentitytype`,
    allLogs: `${Base}log`,
    logMessageById: `${Base}log/logmessagetype/`,
    logIdentity: `${Base}log/identity/`,
  },
  ProofOfPlay: {
    proofDataById: `${Base}proofofplay`,
    playerDescription: `${Base}players/filters/player`,
    fileData: `${Base}tags`,
    getLocation: `${Base}location`,
    exportToExcel: `${Base}proofofplay/excel`,
  },
  Mailbox: {
    sentmails: `${Base}message/sent`,
    recievedmails: `${Base}message`,
    accounts: `${Base}account/contacts`,
    newUserMail: `${Base}message`,
  },
  template: {
    templateSide: `${Base}template`,
    duplicateTemplate: `${Base}template/duplicate`,
    syncTemplate: `${Base}players/gcm/new_template`,
    editTemplate: `${Base}template/`,
    deleteTemplate: `${Base}template/`,
    sendToPlayer: `${Base}players/gcm/new_template`,
    templateZone: `${Base}template/zones/`,
    templatePlaylist: `${Base}media/playlist/`,
    getLayout: `${Base}layout`,
    createTempalte: `${Base}template/`,
    addLayout: `${Base}layout`,
    addTemplate: `${Base}template/`,
    editLayout: `${Base}layout/`,
    layoutById: `${Base}layout/zones/`,
    zonePlaylistDuration: `${Base}playlist/duration/`,
  },
  widget: {
    uploadWidget: `${Base}gallery/uploadfile`,
    saveWidget: `${Base}gallery/widgetsaveas/`,
    ReplaceWidget: `${Base}gallery/replacefile/`,
  },
};

export default API;
